analyzer:
  errors:
    unnecessary_library_name: ignore
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # ✅ Best Practices
    always_declare_return_types: true
    avoid_print: true
    avoid_relative_lib_imports: true
    cancel_subscriptions: true
    close_sinks: true
    comment_references: true
    exhaustive_cases: true
    prefer_relative_imports: true
    use_super_parameters: true

    # ✅ Performance & Optimization
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_const_declarations: true
    unawaited_futures: true
    avoid_unnecessary_containers: true
    avoid_init_to_null: true

    # ✅ Readability & Maintainability
    annotate_overrides: true
    prefer_final_fields: true
    prefer_final_locals: true
    prefer_expression_function_bodies: true
    require_trailing_commas: true
    use_full_hex_values_for_flutter_colors: true
    prefer_single_quotes: true

    # ✅ Safety & Code Quality
    avoid_empty_else: true
    avoid_setters_without_getters: true
    avoid_catches_without_on_clauses: true
    avoid_classes_with_only_static_members: true
    avoid_function_literals_in_foreach_calls: true
    avoid_positional_boolean_parameters: true
    parameter_assignments: true

    # ✅ Flutter-Specific Best Practices
    flutter_style_todos: true
    prefer_mixin: true
    sized_box_for_whitespace: true
    use_key_in_widget_constructors: true

    # ✅ Code Consistency
    constant_identifier_names: true
    curly_braces_in_flow_control_structures: true
    library_prefixes: true
    file_names: true
    unnecessary_null_checks: true
